version: '3'
services:

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    env_file:
      - ./docker/app/.env
    ports:
      - 8080:8080
    depends_on:
      - db
    command: /bin/sh -c 'while ! nc -z db 5432; do sleep 1; done; ./docker/app/bin/init.sh;'
    restart: always

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: pass1
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    restart: always